# Включи мышь
set -g mouse on

# Префикс Ctrl+Space (удобнее Ctrl+B)
set -g prefix C-g
unbind C-b
bind C-g send-prefix

# VI режим (как Helix)
setw -g mode-keys vi
set -g status-keys vi

# 24-бит цвет (для bat/rg/kitty)
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"

# Pane split (твои горячие клавиши)
bind-key "\\" split-window -h -c "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"

# Resize panes
# По горизонтали
bind -n C-M-Left resize-pane -L 5
bind -n C-M-Right resize-pane -R 5

# По вертикали
bind -n M-Up resize-pane -U 5
bind -n M-Down resize-pane -D 5

# Status bar (тёмная тема как zellij)
set -g status on
set -g status-interval 1
set -g status-style 'bg=#1e1e2e,fg=#cdd6f4'
set -g status-left '#[fg=#89b4fa,bg=default] #S '
set -g status-right '#(/home/belousov/.local/myscripts/git-tmux-info.sh #{pane_current_path}) #[fg=cyan]%H:%M %d-%b-%y'

# Window стиль
setw -g window-status-current-style 'bg=#89b4fa,fg=#1e1e2e,bold'
setw -g window-status-style 'bg=#313244,fg=#cdd6f4'

# Автоматическое переименование окон
setw -g automatic-rename on
setw -g automatic-rename-format '#{b:pane_current_path}'

# Вкладки без префикса (Alt)
bind-key -n M-Left previous-window           # Alt+←
bind-key -n M-Right next-window              # Alt+→

# С префиксом, создать вкладку (остаётся для надёжности)
bind-key t new-window -c "#{pane_current_path}"

# Навигация ПАНЕЛЯМИ (panes) — Alt+Shift
bind-key -n M-S-Left select-pane -L          # Alt+Shift+←  влево
bind-key -n M-S-Right select-pane -R         # Alt+Shift+→  вправо  
bind-key -n M-S-Up select-pane -U            # Alt+Shift+↑  вверх
bind-key -n M-S-Down select-pane -D          # Alt+Shift+↓  вниз
